---

# fact etcd, master, node set in 10-consul.yaml line 32 - 34
- name: configure-etcd-leave | create leave cluster etcd service
  set_fact:
    cluster_etcd_leave: |
      #!/bin/bash
      CLEANUP_NEEDED=$(curl -sS http://{{ consul }}:{{ consul_port }}/v1/kv/{{ cluster_name }}/{{ identity }}/cleanup/{{ ansible_hostname }})
      if [ -z "$CLEANUP_NEEDED" ]; then
        echo Cleanup is not needed
        exit 0
      fi
      echo remove {{ ansible_hostname }} from etcd cluster
      echo get RaftID
      REMOVE_NODE=$(/usr/local/bin/etcdctl --ca-file=/etc/ssl/etcd/ssl/ca.pem --cert-file=/etc/ssl/etcd/ssl/member-{{ ansible_hostname }}.pem --key-file=/etc/ssl/etcd/ssl/member-{{ ansible_hostname }}-key.pem --endpoint=https://127.0.0.1:2379 member list | grep {{ansible_hostname}} | awk {'print $1'} | tr -d :)
      echo remove $REMOVE_NODE from etcd cluster
      /usr/local/bin/etcdctl --ca-file=/etc/ssl/etcd/ssl/ca.pem --cert-file=/etc/ssl/etcd/ssl/member-{{ ansible_hostname }}.pem --key-file=/etc/ssl/etcd/ssl/member-{{ ansible_hostname }}-key.pem --endpoint=https://127.0.0.1:2379 member remove $REMOVE_NODE
      echo end script

- name: configure-etcd-leave | copy leave script to destination
  copy:
    content: "{{ cluster_etcd_leave }}"
    dest: /usr/local/bin/kubernetes-scripts/remove-etcd-node
    mode: 0755

- name: configure-etcd-leave | template systemd unit
  set_fact:
    cluster_etcd_leave_systemd: |
      [Unit]
      Description=Remove etcd node "%H" from cluster
      Before=halt.target shutdown.target
      After=etcd.service

      [Service]
      ExecStart=/bin/true
      ExecStop=/usr/local/bin/kubernetes-scripts/remove-etcd-node
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

- name: configure-etcd-leave | copy cluster_etcd_leave
  copy:
    content: "{{ cluster_etcd_leave_systemd }}"
    dest: /etc/systemd/system/cluster-etcd-leave.service
    mode: 0655

- name: configure-etcd-leave | activate and enable cluster-etcd-leave.service
  systemd:
    name: cluster-etcd-leave.service
    state: started
    daemon_reload: yes
    enabled: yes
